/**
 * Staff / Owner "Sign in with Google" — OAuth 2.0 authorization-code flow + PKCE.
 *
 *   GET /api/admin/auth/google/start
 *       — 302 to Google's consent screen with state + PKCE challenge + nonce.
 *   GET /api/admin/auth/google/callback
 *       — verify state, exchange the code SERVER-SIDE, verify the id_token
 *         claims, resolve the verified email against the `users` table, and —
 *         only if it maps to a provisioned staff member — mint a
 *         `warehouse14.session` and hand it back. An unknown email is refused.
 *
 * This is the STAFF door. It deliberately mirrors routes/storefront-auth-google.ts
 * (the customer door) but differs in one decisive way:
 *
 *   • The customer door CREATES an account for any verified Google email.
 *   • The staff door creates NOTHING. It resolves the email against the pre-
 *     provisioned `users` table and 403s anything it does not find. The role
 *     (ADMIN / CASHIER / READONLY) and the `is_owner` bit come from that row —
 *     never from Google, never from the client. Google proves IDENTITY; the
 *     server assigns AUTHORITY. Provisioning is admin-mediated (migrator role):
 *     see scripts/provision-staff.ts. A compromised app role cannot mint a staff
 *     account because it cannot write `users.role` / `users.is_owner`.
 *
 * Two locks stack:
 *   1. Google — the staff OAuth client's consent screen is org-restricted
 *      (Workspace-internal), so Google itself refuses any account outside the
 *      warehouse14.de organisation before the request ever reaches us.
 *   2. Us — the email must resolve to an active `users` row. Belt and braces.
 *
 * The session it mints is byte-for-byte the same shape as routes/auth-pin.ts:
 * a row in `sessions` (TTL 30d Owner / 8h staff), the `warehouse14.session`
 * cookie, AND the token echoed in the response so the Tauri/RN clients can carry
 * it as a Bearer header (the cross-site cookie is dropped by Windows WebView2).
 * Because a Google login is a full, fresh authentication, `last_pin_step_up_at`
 * is stamped now so step-up-gated actions work immediately after sign-in.
 */

import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { and, eq, isNull } from 'drizzle-orm';
import type { FastifyPluginAsync, FastifyReply, FastifyRequest } from 'fastify';

import { auditLog, sessions } from '@norns/db/schema';

import type { Env } from '../config/env.js';
import { sessionTtlMs } from '../lib/session-ttl.js';

const GOOGLE_AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth';
const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
/** Short-lived cookie holding the signed PKCE/state payload during the round-trip. */
const OAUTH_STATE_COOKIE = 'warehouse14.gauth.admin';
const OAUTH_STATE_PATH = '/api/admin/auth/google';
const STATE_TTL_MS = 10 * 60 * 1000; // 10 minutes to complete the consent.

/** Session lifetimes — identical to routes/auth-pin.ts (ADR-0022 §2). */
// Session TTLs are centralized in session-ttl.ts (owner shortened 30d→7d,
// security review 2026-07-21).
/** Device-handoff window: how long a completed login waits to be claimed. */
const HANDOFF_TTL_MS = 5 * 60 * 1000; // 5 minutes

interface StatePayload {
  state: string;
  codeVerifier: string;
  nonce: string;
  returnTo: string;
  /**
   * Optional opaque device-handoff key generated by a NATIVE client (desktop /
   * mobile) that cannot receive a browser redirect. When present, the callback
   * parks the minted session under this key instead of redirecting, and the app
   * retrieves it once via POST /claim. This is the OAuth device-grant shape
   * (RFC 8628-style) adapted to our server-brokered flow — no loopback listener
   * and no custom URL scheme is required on the client.
   */
  deviceNonce?: string;
  exp: number;
}

/** A completed-but-unclaimed login, keyed by the client's deviceNonce. */
interface Handoff {
  /**
   * SHA-256 des Geheimnisses, das beim Google-Ruecklauf als `httpOnly`-Keks in
   * den Browser ging. `/confirm` verlangt es.
   *
   * ⚠️ Hier liegt bewusst nur der ABDRUCK. Sonst stuende in einem
   * Speicherabzug oder einem versehentlichen Protokollsatz das Geheimnis
   * selbst. Siehe lib/uebergabe-browserbindung.ts.
   */
  browserAbdruck?: string;

  token: string;
  actor: { id: string; role: string; isOwner: boolean };
  /** The verified Google identity, for the header profile (never an auth secret). */
  profile: { email: string; displayName: string | null; avatarUrl: string | null };
  sessionExpiresAt: string;
  createdAt: number;
}

/**
 * In-memory device-handoff store. A handoff lives for at most HANDOFF_TTL_MS and
 * is single-use (deleted on claim). In-memory is correct here: it is a few-second
 * bridge between the browser finishing consent and the native app polling /claim;
 * on the rare API restart mid-login the user simply signs in again. The token
 * itself is a real, persisted `sessions` row — only the short-lived NONCE→token
 * pointer is in memory. The nonce (>= 16 random chars) is the capability.
 */
const handoffs = new Map<string, Handoff>();

/**
 * ⚠️ NOCH NICHT BESTAETIGTE UEBERGABEN.
 *
 * Der Angriff, der diesen Zwischenschritt noetig macht, braucht keinen
 * Fehler in unserer Kryptografie:
 *
 *   1. Der Angreifer waehlt eine Kennung N und schickt dem Opfer einen Link
 *      auf `/start?nonce=N`. Der Link zeigt auf die ECHTE Firmenadresse und
 *      sieht vollkommen unverdaechtig aus.
 *   2. Das Opfer meldet sich mit seinem ECHTEN Google-Konto an.
 *   3. Der Angreifer holt die fertige Sitzung mit `POST /claim { nonce: N }`.
 *      Ohne Anmeldung, ohne Geraet, ohne alles.
 *
 * Der Kommentar an `/claim` sagte, die unerratbare Kennung SEI die Berechtigung.
 * Das stimmt nur, solange der SERVER sie erzeugt. Waehlt der Aufrufer sie, weiss
 * der Angreifer sie per Konstruktion.
 *
 * Und eine servergenerierte Kennung allein hilft nicht: der Angreifer kann sich
 * selbst eine holen und DIESE verschicken.
 *
 * Was wirklich schuetzt, ist das, was RFC 8628 hat und uns fehlte: **ein Mensch
 * sieht, was er freigibt, und sagt ja.** Der Kommentar nannte den Weg
 * „RFC 8628-style", aber dort erzeugt der Server den Code UND der Mensch
 * bestaetigt ihn sichtbar. Beides fehlte.
 *
 * Deshalb landet eine fertige Anmeldung ab dem 26.07.2026 zuerst HIER und
 * wandert erst nach einem ausdruecklichen Klick nach `handoffs`. Die Apps
 * muessen dafuer nicht geaendert werden: sie pollen weiter und bekommen so
 * lange `pending`, bis der Mensch bestaetigt hat.
 */
const pendingConfirm = new Map<string, Handoff>();

/** Opaque nonce from a native client — accept only a plausible URL-safe token. */
function sanitizeNonce(v: unknown): string | null {
  if (typeof v !== 'string') return null;
  if (v.length < 16 || v.length > 128) return null;
  return /^[A-Za-z0-9_-]+$/.test(v) ? v : null;
}

/** Drop expired handoffs (called opportunistically on each store/claim). */
function sweepHandoffs(now: number): void {
  for (const [k, v] of pendingConfirm) {
    if (now - v.createdAt > HANDOFF_TTL_MS) pendingConfirm.delete(k);
  }
  for (const [k, h] of handoffs) {
    if (now - h.createdAt > HANDOFF_TTL_MS) handoffs.delete(k);
  }
}

/** The page shown in the system browser after a native-client login completes. */
/**
 * Ein kurzer, ablesbarer Code aus der Kennung.
 *
 * Er ist KEIN Geheimnis und soll keines sein. Sein Zweck ist der Vergleich:
 * das Geraet zeigt denselben Code, und wer keinen Code vor sich hat, hat auch
 * kein Geraet in diesem Vorgang — und darf nicht bestaetigen.
 */
function ablesbarerCode(nonce: string): string {
  const h = createHash('sha256').update(nonce).digest('base64url').toUpperCase();
  const nur = h.replace(/[^A-Z0-9]/g, '').replace(/[IO01]/g, 'X');
  return `${nur.slice(0, 4)}-${nur.slice(4, 8)}`;
}

const esc = (v: string): string =>
  v.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Die Seite, die den Angriff kostet.
 *
 * Sie sagt in einem Satz, was JETZT passiert, und verlangt eine Handlung. Ein
 * Opfer, das nur „sich anmelden" wollte und liest, dass ein GERAET diese
 * Anmeldung erhaelt, hat hier die Gelegenheit anzuhalten. Ohne diese Seite gab
 * es die Gelegenheit nicht: die Sitzung war schon abgeholt, bevor die
 * Erfolgsmeldung erschien.
 */
import {
  ADMIN_KEKS_PFAD,
  ADMIN_UEBERGABE_KEKS,
  bindungStimmt,
  keksOptionen,
  neueBrowserbindung,
} from '../lib/uebergabe-browserbindung.js';

function confirmPage(nonce: string, email: string, returnTo: string): string {
  const code = ablesbarerCode(nonce);
  return `<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Gerät anmelden?</title><style>
:root{color-scheme:light dark}
body{margin:0;min-height:100vh;display:grid;place-items:center;font-family:system-ui,-apple-system,sans-serif;
background:#faf8f3;color:#1c1813}
@media(prefers-color-scheme:dark){body{background:#151310;color:#f1ebde}}
.c{text-align:center;max-width:26rem;padding:2rem}
h1{font-size:1.25rem;margin:0 0 .6rem}
p{color:#7a7061;margin:.5rem 0;font-size:.95rem;line-height:1.5}
@media(prefers-color-scheme:dark){p{color:#a79d89}}
.code{font-family:ui-monospace,SFMono-Regular,monospace;font-size:2rem;letter-spacing:.18em;
margin:1.2rem 0;padding:.7rem 1rem;border:2px solid #9c2630;border-radius:.5rem;display:inline-block}
.warn{background:#fdf2f2;border-left:3px solid #9c2630;padding:.8rem 1rem;text-align:left;
margin:1.2rem 0;font-size:.88rem;color:#6b2020}
@media(prefers-color-scheme:dark){.warn{background:#2a1414;color:#e8a0a0}}
button{font:inherit;font-size:1rem;padding:.8rem 1.8rem;border:0;border-radius:.4rem;
background:#9c2630;color:#fff;cursor:pointer}
button:disabled{opacity:.5;cursor:default}
.no{background:none;color:#7a7061;text-decoration:underline;padding:.6rem}
</style></head><body><div class="c">
<h1>Ein Gerät möchte sich anmelden</h1>
<p>Als <strong>${esc(email)}</strong></p>
<div class="code">${esc(code)}</div>
<div class="warn">
<strong>Dieser Code muss auf Ihrem Gerät stehen.</strong><br>
Sehen Sie ihn dort nicht, oder haben Sie gerade kein Gerät angemeldet, dann
brechen Sie ab. Jemand anders würde sonst mit Ihrem Zugang arbeiten.
</div>
<form method="POST" action="/api/admin/auth/google/confirm">
<input type="hidden" name="nonce" value="${esc(nonce)}">
<input type="hidden" name="returnTo" value="${esc(returnTo)}">
<button type="submit">Ja, das ist mein Gerät</button>
</form>
<p><a class="no" href="about:blank">Abbrechen</a></p>
</div></body></html>`;
}

const SUCCESS_PAGE = `<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Angemeldet</title><style>
:root{color-scheme:light dark}
body{margin:0;height:100vh;display:grid;place-items:center;font-family:system-ui,-apple-system,sans-serif;
background:#faf8f3;color:#1c1813}
@media(prefers-color-scheme:dark){body{background:#151310;color:#f1ebde}}
.c{text-align:center;max-width:22rem;padding:2rem}
.m{width:56px;height:56px;border-radius:50%;margin:0 auto 1.2rem;display:grid;place-items:center;
background:#e2f0e7;color:#1f6b47;font-size:1.8rem}
@media(prefers-color-scheme:dark){.m{background:#16321f;color:#6fcb98}}
h1{font-size:1.3rem;margin:0 0 .4rem}p{color:#7a7061;margin:.2rem 0;font-size:.95rem}
@media(prefers-color-scheme:dark){p{color:#a79d89}}
</style></head><body><div class="c"><div class="m">&#10003;</div>
<h1>Angemeldet</h1><p>Sie k&ouml;nnen dieses Fenster schlie&szlig;en und zu Warehouse14 zur&uuml;ckkehren.</p>
</div></body></html>`;

/**
 * Rücksprung-Seite zum App-Schema, mit sichtbarem Knopf.
 *
 * Ein nacktes 302 auf `warehouse14://…` klemmt auf Android: Chrome (Custom
 * Tabs) blockiert eine AUTOMATISCHE Navigation zu einem App-Schema ohne
 * Nutzergeste, der Tab bleibt auf einer leeren Seite stehen und die Anmeldung
 * „hängt" (Basels Befund am 24.07.2026, zwei Updates in Folge). Diese Seite
 * VERSUCHT die automatische Weiterleitung (meta refresh + location.replace,
 * beide greifen dort, wo die Richtlinie es zulässt, z. B. iOS) und trägt IMMER
 * einen großen Knopf: das Tippen ist eine Geste, die nie blockiert wird.
 *
 * Der Token steht ausschließlich im URL-FRAGMENT des Sprungziels (wie zuvor
 * beim 302), taucht also in keinem Zugriffprotokoll auf. Das Ziel ist durch
 * `sanitizeReturnTo` auf das App-Schema begrenzt; fürs HTML-Attribut wird es
 * zusätzlich escaped.
 */
function sendAppReturnPage(
  reply: FastifyReply,
  target: string,
  title: string,
  line: string,
): FastifyReply {
  const href = target.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
  const js = JSON.stringify(target);
  reply.header('content-type', 'text/html; charset=utf-8');
  reply.header('cache-control', 'no-store');
  return reply.send(`<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="0;url=${href}">
<title>${title}</title><style>
:root{color-scheme:light dark}
body{margin:0;height:100vh;display:grid;place-items:center;font-family:system-ui,-apple-system,sans-serif;
background:#faf8f3;color:#1c1813}
@media(prefers-color-scheme:dark){body{background:#151310;color:#f1ebde}}
.c{text-align:center;max-width:22rem;padding:2rem}
h1{font-size:1.3rem;margin:0 0 .4rem}p{color:#7a7061;margin:.2rem 0 1.2rem;font-size:.95rem}
@media(prefers-color-scheme:dark){p{color:#a79d89}}
a.b{display:inline-block;padding:.85rem 1.6rem;border-radius:.75rem;background:#a3823b;color:#fff;
text-decoration:none;font-weight:600;font-size:1rem}
</style></head><body><div class="c">
<h1>${title}</h1><p>${line}</p>
<a class="b" href="${href}">Zur&uuml;ck zur App</a>
<script>location.replace(${js})</script>
</div></body></html>`);
}

/** Random URL-safe token. */
function randomToken(): string {
  return randomBytes(32).toString('base64url');
}

/** HMAC-SHA256(payload, secret) → base64url. */
function hmac(payload: string, secret: string): string {
  return createHmac('sha256', secret).update(payload).digest('base64url');
}

/** Sign a state payload as `<base64url(json)>.<mac>`. */
function signState(p: StatePayload, secret: string): string {
  const body = Buffer.from(JSON.stringify(p)).toString('base64url');
  return `${body}.${hmac(body, secret)}`;
}

/** Verify + parse a signed state cookie. Returns null on any tamper/expiry. */
function verifyState(raw: string | undefined, secret: string): StatePayload | null {
  if (!raw) return null;
  const dot = raw.lastIndexOf('.');
  if (dot <= 0) return null;
  const body = raw.slice(0, dot);
  const mac = raw.slice(dot + 1);
  const expected = hmac(body, secret);
  if (mac.length !== expected.length) return null;
  if (!timingSafeEqual(Buffer.from(mac), Buffer.from(expected))) return null;
  try {
    const p = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as StatePayload;
    if (!p || typeof p.exp !== 'number' || p.exp < Date.now()) return null;
    return p;
  } catch {
    return null;
  }
}

/** Decode (NOT verify-signature) a JWT's payload claims. */
function decodeJwtClaims(jwt: string): Record<string, unknown> | null {
  const parts = jwt.split('.');
  if (parts.length !== 3) return null;
  try {
    return JSON.parse(Buffer.from(parts[1] ?? '', 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

/**
 * Where the callback may hand the freshly-minted session back to. The native
 * clients cannot read an httpOnly cross-site cookie, so they open the system
 * browser at `/start?returnTo=…` and receive the token via this redirect.
 * Allowed targets ONLY:
 *   • a same-site relative path (`/…`, not `//…`)  — browser testing
 *   • the app deep-link scheme `warehouse14://…`    — Android / iOS owner app
 *   • loopback `http://localhost[:port]` / `127.0.0.1` — desktop (Tauri) app
 * Anything else is an open-redirect vector and is rejected → JSON response.
 */
function sanitizeReturnTo(v: unknown): string | null {
  if (typeof v !== 'string' || v.length === 0 || v.length > 512) return null;
  if (v.startsWith('/') && !v.startsWith('//')) return v;
  if (v.startsWith('warehouse14://')) return v;
  if (/^http:\/\/(localhost|127\.0\.0\.1)(:\d{1,5})?(\/|$)/.test(v)) return v;
  return null;
}

/** Append a URL fragment (never a query — fragments are not written to access logs). */
function withFragment(target: string, params: Record<string, string>): string {
  const frag = new URLSearchParams(params).toString();
  const sep = target.includes('#') ? '&' : '#';
  return `${target}${sep}${frag}`;
}

function redirectUriFor(baseUrl: string): string {
  return `${baseUrl.replace(/\/+$/, '')}/api/admin/auth/google/callback`;
}

const adminGoogleAuthRoutes: FastifyPluginAsync<{ env: Env }> = async (app, opts) => {
  const { env } = opts;

  function configured(): boolean {
    return !!(env.GOOGLE_STAFF_CLIENT_ID && env.GOOGLE_STAFF_CLIENT_SECRET && env.ADMIN_PUBLIC_URL);
  }

  /** Set the staff session cookie — identical attributes to routes/auth-pin.ts. */
  function setSessionCookie(reply: FastifyReply, token: string, expiresAt: Date): void {
    const crossSite = process.env.NODE_ENV === 'production';
    reply.setCookie('warehouse14.session', token, {
      httpOnly: true,
      secure: crossSite ? true : false,
      sameSite: crossSite ? 'none' : 'lax',
      path: '/',
      expires: expiresAt,
    });
  }

  // ── GET /api/admin/auth/google/start ─────────────────────────────────
  app.get(
    '/api/admin/auth/google/start',
    {
      schema: {
        tags: ['auth'],
        summary: 'Begin staff Sign-in-with-Google (302 to Google).',
        security: [],
        hide: true,
      },
    },
    async (
      req: FastifyRequest<{ Querystring: { returnTo?: string; nonce?: string } }>,
      reply: FastifyReply,
    ) => {
      if (!configured()) {
        return reply.status(503).send({
          error: { code: 'NOT_CONFIGURED', message: 'Google-Anmeldung ist nicht eingerichtet.' },
        });
      }
      const codeVerifier = randomToken();
      const codeChallenge = createHash('sha256').update(codeVerifier).digest('base64url');
      const payload: StatePayload = {
        state: randomToken(),
        codeVerifier,
        nonce: randomToken(),
        returnTo: sanitizeReturnTo(req.query.returnTo) ?? '',
        exp: Date.now() + STATE_TTL_MS,
      };
      const dn = sanitizeNonce(req.query.nonce);
      if (dn) payload.deviceNonce = dn;
      reply.setCookie(OAUTH_STATE_COOKIE, signState(payload, env.AUTH_SECRET), {
        path: OAUTH_STATE_PATH,
        httpOnly: true,
        sameSite: 'lax',
        secure: process.env.NODE_ENV === 'production',
        maxAge: Math.floor(STATE_TTL_MS / 1000),
      });

      const url = new URL(GOOGLE_AUTH_URL);
      url.searchParams.set('client_id', env.GOOGLE_STAFF_CLIENT_ID);
      url.searchParams.set('redirect_uri', redirectUriFor(env.ADMIN_PUBLIC_URL));
      url.searchParams.set('response_type', 'code');
      url.searchParams.set('scope', 'openid email profile');
      url.searchParams.set('state', payload.state);
      url.searchParams.set('nonce', payload.nonce);
      url.searchParams.set('code_challenge', codeChallenge);
      url.searchParams.set('code_challenge_method', 'S256');
      url.searchParams.set('access_type', 'online');
      url.searchParams.set('prompt', 'select_account');
      // Hint Google to pre-select the Workspace org. Not a security boundary
      // (the org-restricted consent screen + the users-table lookup are), just UX.
      if (env.STAFF_GOOGLE_HD) url.searchParams.set('hd', env.STAFF_GOOGLE_HD);
      return reply.redirect(url.toString());
    },
  );

  // ── GET /api/admin/auth/google/callback ──────────────────────────────
  app.get(
    '/api/admin/auth/google/callback',
    {
      schema: {
        tags: ['auth'],
        summary: 'Staff Google OAuth callback — exchange code, resolve role, sign in.',
        security: [],
        hide: true,
      },
    },
    async (
      req: FastifyRequest<{ Querystring: { code?: string; state?: string; error?: string } }>,
      reply: FastifyReply,
    ) => {
      if (!configured()) {
        return reply.status(503).send({
          error: { code: 'NOT_CONFIGURED', message: 'Google-Anmeldung ist nicht eingerichtet.' },
        });
      }

      const raw = (req.cookies as Record<string, string | undefined>)?.[OAUTH_STATE_COOKIE];
      reply.clearCookie(OAUTH_STATE_COOKIE, { path: OAUTH_STATE_PATH });

      const q = req.query;
      const st = verifyState(raw, env.AUTH_SECRET);
      const returnTo = st ? sanitizeReturnTo(st.returnTo) : null;

      /** Deny: return-to-app page with an error fragment, else a JSON status.
       *  Dieselbe Knopf-Seite wie der Erfolgsweg, aus demselben Grund: ein
       *  automatischer Sprung zum App-Schema wird ohne Geste blockiert. */
      const deny = (status: number, code: string, message: string) => {
        if (returnTo) {
          return sendAppReturnPage(
            reply,
            withFragment(returnTo, { error: code }),
            'Anmeldung nicht m&ouml;glich',
            'Die Anmeldung wurde nicht abgeschlossen. Zur&uuml;ck zur App:',
          );
        }
        return reply.status(status).send({ error: { code, message } });
      };

      if (q.error || !q.code || !q.state) return deny(400, 'OAUTH_FAILED', 'Anmeldung abgebrochen.');
      if (!st || st.state !== q.state) return deny(400, 'OAUTH_FAILED', 'Ungültiger Anmeldeversuch.');

      // Exchange the code SERVER-SIDE (client secret + PKCE verifier).
      let claims: Record<string, unknown> | null = null;
      try {
        const tokenResp = await fetch(GOOGLE_TOKEN_URL, {
          method: 'POST',
          headers: { 'content-type': 'application/x-www-form-urlencoded' },
          body: new URLSearchParams({
            code: q.code,
            client_id: env.GOOGLE_STAFF_CLIENT_ID,
            client_secret: env.GOOGLE_STAFF_CLIENT_SECRET,
            redirect_uri: redirectUriFor(env.ADMIN_PUBLIC_URL),
            grant_type: 'authorization_code',
            code_verifier: st.codeVerifier,
          }),
          signal: AbortSignal.timeout(10_000),
        });
        if (!tokenResp.ok) return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
        const tokens = (await tokenResp.json()) as { id_token?: string };
        if (!tokens.id_token) return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
        claims = decodeJwtClaims(tokens.id_token);
      } catch {
        return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
      }
      if (!claims) return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');

      // Verify the id_token claims (token came DIRECTLY from Google over TLS, so
      // per OIDC Core §3.1.3.7 signature re-verification is not strictly required;
      // we still verify iss / aud / exp / nonce / email_verified).
      const iss = String(claims.iss ?? '');
      if (iss !== 'https://accounts.google.com' && iss !== 'accounts.google.com') {
        return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
      }
      if (String(claims.aud ?? '') !== env.GOOGLE_STAFF_CLIENT_ID) {
        return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
      }
      const exp = typeof claims.exp === 'number' ? claims.exp : 0;
      if (exp * 1000 < Date.now()) return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
      if (String(claims.nonce ?? '') !== st.nonce) {
        return deny(400, 'OAUTH_FAILED', 'Anmeldung fehlgeschlagen.');
      }

      const email = String(claims.email ?? '')
        .trim()
        .toLowerCase();
      const emailVerified = claims.email_verified === true || claims.email_verified === 'true';
      const sub = String(claims.sub ?? '');
      if (!email || !emailVerified || !sub) {
        return deny(403, 'FORBIDDEN', 'Dieses Konto ist nicht freigeschaltet.');
      }

      // THE AUTHORISATION GATE: the email must resolve to an ACTIVE staff row.
      // Not found (or soft-deleted) → 403. Nothing is created here, ever.
      const staff = await app.db.query.users.findFirst({
        where: (u) => and(eq(u.email, email), isNull(u.softDeletedAt)),
        columns: { id: true, role: true, isOwner: true, preferredLanguage: true },
      });
      if (!staff) {
        const ip = req.ip ?? null;
        await app.db.insert(auditLog).values({
          eventType: 'auth.google_denied',
          actorUserId: null,
          deviceId: null,
          ipAddress: ip,
          userAgent: (req.headers['user-agent'] as string | undefined) ?? null,
          payload: { email, reason: 'not_provisioned' },
        });
        return deny(403, 'FORBIDDEN', 'Dieses Konto ist nicht freigeschaltet.');
      }

      // Mint the session — identical shape to routes/auth-pin.ts. Google login is
      // a full fresh authentication, so stamp a fresh step-up. No device binding:
      // the Google path does not carry mTLS device identity (device_id stays null).
      const ttlMs = sessionTtlMs(staff.isOwner);
      const sessionId = randomUUID();
      const token = randomUUID().replace(/-/g, '') + randomUUID().replace(/-/g, '');
      const expiresAt = new Date(Date.now() + ttlMs);
      const ip = req.ip ?? null;
      const userAgent = (req.headers['user-agent'] as string | undefined) ?? null;

      await app.db.transaction(async (tx) => {
        await tx.insert(sessions).values({
          id: sessionId,
          userId: staff.id,
          token,
          expiresAt,
          ipAddress: ip,
          userAgent,
          deviceId: null,
          lastPinStepUpAt: new Date(),
        });
        await tx.insert(auditLog).values({
          eventType: 'auth.google_login',
          actorUserId: staff.id,
          deviceId: null,
          ipAddress: ip,
          userAgent,
          payload: { email, sub, isOwner: staff.isOwner, role: staff.role },
        });
      });

      setSessionCookie(reply, token, expiresAt);

      const sessionExpiresAt = expiresAt.toISOString();
      const actor = { id: staff.id, role: staff.role, isOwner: staff.isOwner };

      // The verified Google identity for the header profile. `name`/`picture`
      // come from the `profile` scope; keep them null-safe (a Workspace account
      // may omit either). This is display-only — authority is `actor`, above.
      const displayName =
        typeof claims.name === 'string' && claims.name.trim() ? claims.name.trim() : null;
      const avatarUrl =
        typeof claims.picture === 'string' && claims.picture.trim() ? claims.picture.trim() : null;
      const profile = { email, displayName, avatarUrl };

      // (1) Native device-handoff: park the session under the nonce so the app
      // can retrieve it via POST /claim. NOT exclusive with the deep link below:
      // a mobile client may send BOTH (nonce as the robust path, returnTo as the
      // fast path) — park first, then fall through to the redirect page.
      if (st.deviceNonce) {
        const now = Date.now();
        sweepHandoffs(now);
        // NICHT mehr direkt in `handoffs`. Erst muss ein Mensch bestaetigen,
        // dass er wirklich ein GERAET anmelden wollte. Siehe die Erklaerung
        // bei `pendingConfirm`.
        // ⚠️ Die Bestaetigung gehoert dem Browser, der sich GERADE angemeldet
        // hat. Ohne diese Bindung genuegte die Kennung, und die kennt der
        // Angreifer per Konstruktion — er hat sie ja gewaehlt. Siehe
        // lib/uebergabe-browserbindung.ts.
        const bindung = neueBrowserbindung();
        pendingConfirm.set(st.deviceNonce, {
          token,
          actor,
          profile,
          sessionExpiresAt,
          createdAt: now,
          browserAbdruck: bindung.abdruck,
        });
        reply.setCookie(
          ADMIN_UEBERGABE_KEKS,
          bindung.geheimnis,
          keksOptionen(ADMIN_KEKS_PFAD, env.NODE_ENV === 'production'),
        );
        reply.header('content-type', 'text/html; charset=utf-8');
        return reply.send(confirmPage(st.deviceNonce, email, returnTo ?? ''));
      }

      // (2) Browser-redirect handoff (a mobile deep link): token in the URL
      // fragment (never the query string, so it is not written to any access log).
      //
      // NICHT als nacktes 302: Chrome auf Android blockiert eine automatische
      // Navigation zu einem App-Schema ohne Nutzergeste — der Custom Tab blieb
      // auf einer leeren Seite haengen und die Anmeldung "klemmte" (Basels
      // Befund, 24.07.2026, zwei Updates in Folge). Stattdessen eine Seite, die
      // die automatische Weiterleitung VERSUCHT und immer einen sichtbaren
      // Knopf traegt: das Tippen ist die Geste, die Chrome nie blockiert.
      if (returnTo) {
        return sendAppReturnPage(
          reply,
          withFragment(returnTo, { token, expiresAt: sessionExpiresAt }),
          'Angemeldet',
          'Sie sind angemeldet. Zur&uuml;ck zur App:',
        );
      }

      // (3) Plain browser test: the same JSON shape as pin-login.
      return { ok: true as const, sessionExpiresAt, actor, profile, token };
    },
  );

  // ── POST /api/admin/auth/google/confirm ──────────────────────────────
  //
  // Der Klick, der die Sitzung freigibt. Bis zum 26.07.2026 gab es ihn nicht:
  // die Sitzung lag abholbereit, sobald Google fertig war, und wer die Kennung
  // kannte, nahm sie. Die Kennung durfte der AUFRUFER waehlen — also wusste sie
  // ein Angreifer per Konstruktion.
  //
  // Diese Route verlangt nichts Geheimes, und das ist Absicht: sie wird aus der
  // Bestaetigungsseite heraus aufgerufen, im Browser des Menschen, der sich
  // gerade angemeldet hat. Der Schutz ist nicht ein Geheimnis, sondern die
  // ENTSCHEIDUNG: der Mensch liest, dass ein GERAET diese Anmeldung bekommt,
  // sieht einen Code, der auf seinem Geraet stehen muesste, und sagt ja.
  //
  // Wer diese Route direkt aufruft, ohne die Seite gesehen zu haben, kann damit
  // nur seine EIGENE Uebergabe freigeben — er kennt ja bereits die Kennung. Er
  // gewinnt nichts, was er nicht schon hatte.
  app.post(
    '/api/admin/auth/google/confirm',
    {
      schema: {
        tags: ['auth'],
        summary: 'Confirm a device handoff after the human has seen what it does.',
        security: [],
        hide: true,
      },
    },
    async (req: FastifyRequest<{ Body: { nonce?: string; returnTo?: string } }>, reply: FastifyReply) => {
      const nonce = sanitizeNonce((req.body ?? {}).nonce);
      reply.header('content-type', 'text/html; charset=utf-8');
      if (!nonce) return reply.status(400).send(SUCCESS_PAGE);

      const now = Date.now();
      sweepHandoffs(now);
      const wartend = pendingConfirm.get(nonce);
      // ⚠️ DIE EIGENTLICHE SCHRANKE. Vorher stand hier nur die Kennung, und
      // die kennt der Angreifer, weil er sie gewaehlt hat: `POST /confirm`
      // plus `POST /claim` genuegten, ganz ohne Menschen. An der offenen
      // Adresse gemessen: 200.
      //
      // Der Keks wird beim Google-Ruecklauf gesetzt und ist `httpOnly` samt
      // `SameSite=Lax`. Wer nur die Kennung hat, hat ihn nicht, und ein
      // fremder POST von einer Angreiferseite fuehrt ihn nicht mit.
      if (wartend && !bindungStimmt(req.cookies?.[ADMIN_UEBERGABE_KEKS], wartend.browserAbdruck)) {
        req.log.warn(
          { code: ablesbarerCode(nonce), hatKeks: Boolean(req.cookies?.[ADMIN_UEBERGABE_KEKS]) },
          'auth.device_handoff.confirm_ohne_browserbindung',
        );
        // Dieselbe Seite wie bei „abgelaufen": fuer einen Probierenden gibt es
        // hier nichts zu lernen.
        return reply.send(SUCCESS_PAGE);
      }
      if (!wartend) {
        // Abgelaufen oder schon bestaetigt. Kein Grund, hier verschiedene
        // Faelle zu unterscheiden: fuer den Menschen sieht beides gleich aus,
        // und fuer einen Probierenden gibt es so nichts zu lernen.
        return reply.send(SUCCESS_PAGE);
      }
      pendingConfirm.delete(nonce);
      reply.clearCookie(ADMIN_UEBERGABE_KEKS, { path: ADMIN_KEKS_PFAD });
      handoffs.set(nonce, wartend);
      req.log.info(
        { actorId: wartend.actor?.id ?? null, code: ablesbarerCode(nonce) },
        'auth.device_handoff.confirmed',
      );
      return reply.send(SUCCESS_PAGE);
    },
  );

  // ── POST /api/admin/auth/google/claim ────────────────────────────────
  // A native client that began login with ?nonce=… polls here to retrieve the
  // minted session exactly once. 200 + session when ready; 202 while the browser
  // leg is still in flight. The nonce is deleted on the first success (single-use),
  // and the unguessable nonce itself is the capability — no session is required.
  app.post(
    '/api/admin/auth/google/claim',
    {
      schema: {
        tags: ['auth'],
        summary: 'Claim a completed device-handoff Google login (native clients).',
        security: [],
        hide: true,
      },
    },
    async (req: FastifyRequest<{ Body: { nonce?: string } }>, reply: FastifyReply) => {
      const nonce = sanitizeNonce((req.body ?? {}).nonce);
      if (!nonce) {
        return reply
          .status(400)
          .send({ error: { code: 'BAD_REQUEST', message: 'nonce fehlt oder ist ungültig.' } });
      }
      const now = Date.now();
      sweepHandoffs(now);
      const h = handoffs.get(nonce);
      if (!h) {
        // Not ready yet (or already claimed / expired) — the client keeps polling.
        // A 200 (not 202) keeps every HTTP client's "success" path simple.
        return { ok: false as const, pending: true };
      }
      handoffs.delete(nonce); // single-use
      return {
        ok: true as const,
        sessionExpiresAt: h.sessionExpiresAt,
        actor: h.actor,
        profile: h.profile,
        token: h.token,
      };
    },
  );

  // 14.08.2026: hier stand der Weg /api/admin/auth/google/native. Sein
  // einziger Rufer war die Inhaber-App aus warehouse14, und die ist mit
  // der Trennung gefallen. Die Kasse meldet sich ueber start/callback an.
};

export default adminGoogleAuthRoutes;
