import { describe, expect, it, vi } from 'vitest';

import {
  ApiCircuitOpenError,
  ApiError,
  ApiNetworkError,
  ApiOfflineQueuedError,
  ApiOutboxConflictError,
} from '../src/errors.js';
import { uuidv7 } from '../src/internal/uuidv7.js';
import type { MiddlewareRequest, MiddlewareResponse, Next } from '../src/middleware.js';
import type { OutboxRecord, OutboxStore } from '../src/middleware/offline-queue.js';
import { isGobdRelevantPath, offlineQueueMiddleware } from '../src/middleware/offline-queue.js';
import { drainOutbox } from '../src/middleware/offline-replay.js';

function createMockRequest(overrides: Partial<MiddlewareRequest> = {}): MiddlewareRequest {
  const controller = new AbortController();
  return {
    method: 'POST',
    url: 'http://localhost/api/ankauf',
    path: '/ankauf',
    headers: {},
    body: { gold_g: 12.4, agreed_price_eur: 720.0 },
    signal: controller.signal,
    meta: { attempt: 1, startedAt: Date.now(), custom: {} },
    ...overrides,
  };
}

function createMockResponse(overrides: Partial<MiddlewareResponse> = {}): MiddlewareResponse {
  return {
    data: { ok: true },
    status: 200,
    headers: new Headers(),
    requestId: 'req_123',
    traceId: 'trace_123',
    ...overrides,
  };
}

/** In-memory OutboxStore double — records enqueues in insertion order. */
function createFakeStore(): OutboxStore & { rows: OutboxRecord[] } {
  const rows: OutboxRecord[] = [];
  return {
    rows,
    enqueue: vi.fn(async (record: OutboxRecord) => {
      rows.push(record);
    }),
    markSucceeded: vi.fn(async () => {}),
    markConflict: vi.fn(async () => {}),
    listPending: vi.fn(async () => rows),
    getStats: vi.fn(async () => ({ pending: rows.length, conflict: 0 })),
  };
}

function makeRecord(idempotencyKey: string, path = '/ankauf'): OutboxRecord {
  return {
    idempotencyKey,
    traceId: null,
    method: 'POST',
    path,
    url: `http://localhost/api${path}`,
    headers: { 'idempotency-key': idempotencyKey },
    body: { k: idempotencyKey },
    enqueuedAt: 1,
    gobdRelevant: true,
    callerSuppliedKey: true,
    deviceId: 'till-01',
  };
}

/** Store double for replay tests — drains a fixed pending list, tracks calls. */
function createReplayStore(pending: OutboxRecord[]): OutboxStore & {
  succeeded: string[];
  conflicts: string[];
} {
  const succeeded: string[] = [];
  const conflicts: string[] = [];
  return {
    succeeded,
    conflicts,
    enqueue: vi.fn(async () => {}),
    markSucceeded: vi.fn(async (key: string) => {
      succeeded.push(key);
    }),
    markConflict: vi.fn(async (key: string) => {
      conflicts.push(key);
    }),
    listPending: vi.fn(async () => pending),
    getStats: vi.fn(async () => ({ pending: pending.length, conflict: conflicts.length })),
  };
}

const deps = (store: OutboxStore, online: boolean, extra = {}) => ({
  store,
  isOnline: () => online,
  deviceId: 'till-01',
  ...extra,
});

describe('offlineQueueMiddleware — passthrough', () => {
  it('never enqueues or keys a GET, even when offline', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, false));
    const req = createMockRequest({ method: 'GET', path: '/products' });
    const res = createMockResponse();
    const next: Next = vi.fn().mockResolvedValue(res);

    const actual = await mw(req, next);

    expect(actual).toBe(res);
    expect(next).toHaveBeenCalledTimes(1);
    expect(store.rows).toHaveLength(0);
    expect(req.headers['idempotency-key']).toBeUndefined();
  });

  it('passes through (no enqueue) when the replay loop sets skipOfflineQueue', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, false));
    const req = createMockRequest({
      meta: { attempt: 1, startedAt: 0, custom: { skipOfflineQueue: true } },
    });
    const next: Next = vi.fn().mockResolvedValue(createMockResponse());

    await mw(req, next);

    expect(next).toHaveBeenCalledTimes(1);
    expect(store.rows).toHaveLength(0);
  });
});

describe('offlineQueueMiddleware — online happy path', () => {
  it('auto-generates an idempotency key for a non-fiscal mutation and forwards', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, true, { generateKey: () => 'gen-key-1' }));
    const req = createMockRequest({ path: '/inventory/adjust' });
    const res = createMockResponse();
    const next: Next = vi.fn().mockResolvedValue(res);

    const actual = await mw(req, next);

    expect(actual).toBe(res);
    expect(req.headers['idempotency-key']).toBe('gen-key-1');
    expect(req.meta.custom?.idempotencyKey).toBe('gen-key-1');
    expect(req.meta.custom?.idempotencyKeyAutoGenerated).toBe(true);
    expect(store.rows).toHaveLength(0);
  });

  it('uses the caller-supplied key for fiscal paths and flags it as not auto-generated', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(
      deps(store, true, { generateKey: () => 'SHOULD-NOT-BE-USED' }),
    );
    const req = createMockRequest({
      meta: { attempt: 1, startedAt: 0, custom: { idempotencyKey: 'caller-key-abc' } },
    });
    const next: Next = vi.fn().mockResolvedValue(createMockResponse());

    await mw(req, next);

    expect(req.headers['idempotency-key']).toBe('caller-key-abc');
    expect(req.meta.custom?.idempotencyKeyAutoGenerated).toBe(false);
    expect(store.rows).toHaveLength(0);
  });
});

describe('offlineQueueMiddleware — enqueue paths', () => {
  it('enqueues immediately without a network attempt when already offline', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, false, { generateKey: () => 'k-offline' }));
    const req = createMockRequest();
    const next: Next = vi.fn();

    const caught = await mw(req, next).catch((e) => e);

    expect(caught).toBeInstanceOf(ApiOfflineQueuedError);
    // No failed attempt happened, so there is no underlying cause.
    expect((caught as ApiOfflineQueuedError).cause).toBeUndefined();
    expect(next).not.toHaveBeenCalled();
    expect(store.rows).toHaveLength(1);
    expect(store.rows[0].idempotencyKey).toBe('k-offline');
  });

  it('enqueues on ApiNetworkError and throws ApiOfflineQueuedError carrying the cause', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, true, { generateKey: () => 'k-net' }));
    const req = createMockRequest();
    const netErr = new ApiNetworkError('connection refused');
    const next: Next = vi.fn().mockRejectedValue(netErr);

    const caught = await mw(req, next).catch((e) => e);

    expect(caught).toBeInstanceOf(ApiOfflineQueuedError);
    expect((caught as ApiOfflineQueuedError).idempotencyKey).toBe('k-net');
    expect((caught as ApiOfflineQueuedError).cause).toBe(netErr);
    expect(store.rows).toHaveLength(1);
    expect(next).toHaveBeenCalledTimes(1);
  });

  it('enqueues on ApiCircuitOpenError (circuit-open is indistinguishable from offline to the cashier)', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, true));
    const req = createMockRequest();
    const circuitErr = new ApiCircuitOpenError('POST /ankauf', Date.now(), 30_000);
    const next: Next = vi.fn().mockRejectedValue(circuitErr);

    const caught = await mw(req, next).catch((e) => e);

    expect(caught).toBeInstanceOf(ApiOfflineQueuedError);
    expect((caught as ApiOfflineQueuedError).cause).toBe(circuitErr);
    expect(store.rows).toHaveLength(1);
  });

  it('does NOT enqueue a genuine ApiError from a reachable server — rethrows it unchanged', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, true));
    const req = createMockRequest();
    const apiErr = new ApiError({
      code: 'VALIDATION_ERROR',
      message: 'bad weight',
      httpStatus: 422,
    });
    const next: Next = vi.fn().mockRejectedValue(apiErr);

    await expect(mw(req, next)).rejects.toBe(apiErr);
    expect(store.rows).toHaveLength(0);
  });
});

describe('offlineQueueMiddleware — outbox record fidelity', () => {
  it('seals method/path/url/headers/body/device and marks gobdRelevant via classifier', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(
      deps(store, false, {
        generateKey: () => 'k-seal',
        classifyGobdRelevant: (path: string) => path.startsWith('/ankauf'),
      }),
    );
    const req = createMockRequest({
      method: 'POST',
      path: '/ankauf',
      url: 'http://localhost/api/ankauf',
      headers: { 'x-existing': 'v' },
      body: { gold_g: 12.4 },
      meta: { attempt: 1, startedAt: 0, traceId: 'trace-xyz', custom: {} },
    });

    await mw(req, vi.fn()).catch(() => {});

    const row = store.rows[0];
    expect(row.method).toBe('POST');
    expect(row.path).toBe('/ankauf');
    expect(row.url).toBe('http://localhost/api/ankauf');
    expect(row.deviceId).toBe('till-01');
    expect(row.callerSuppliedKey).toBe(false);
    expect(row.gobdRelevant).toBe(true);
    expect(row.traceId).toBe('trace-xyz');
    // Headers sealed AFTER the key was stamped on.
    expect(row.headers['idempotency-key']).toBe('k-seal');
    expect(row.headers['x-existing']).toBe('v');
    expect(row.body).toEqual({ gold_g: 12.4 });
  });

  it('honors an explicit meta.custom.gobdRelevant override', async () => {
    const store = createFakeStore();
    const mw = offlineQueueMiddleware(deps(store, false));
    const req = createMockRequest({
      meta: { attempt: 1, startedAt: 0, custom: { gobdRelevant: true } },
    });

    await mw(req, vi.fn()).catch(() => {});

    expect(store.rows[0].gobdRelevant).toBe(true);
  });
});

describe('uuidv7', () => {
  it('produces a canonical v7 UUID (version nibble 7, RFC variant)', () => {
    const id = uuidv7();
    expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  });

  it('is time-ordered: a later timestamp sorts lexicographically after an earlier one', () => {
    const early = uuidv7(1_000_000_000_000);
    const late = uuidv7(2_000_000_000_000);
    expect(early < late).toBe(true);
  });

  it('is unique across many calls in the same millisecond', () => {
    const fixed = 1_700_000_000_000;
    const ids = new Set(Array.from({ length: 1000 }, () => uuidv7(fixed)));
    expect(ids.size).toBe(1000);
  });
});

describe('isGobdRelevantPath (ADR-0044 §5 / action item 7)', () => {
  it('flags finalize, ankauf und storno als fiskal', () => {
    // The api-client posts to the FULL '/api/...' path — the prefixes must match it.
    for (const p of [
      '/api/transactions/ankauf',
      '/api/transactions/finalize',
      '/api/transactions/storno',
    ]) {
      expect(isGobdRelevantPath(p)).toBe(true);
    }
  });

  /**
   * ⚠️ 15.08.2026: hier stand zusätzlich `/api/transactions/return`.
   *
   * Die Route ist an diesem Tag ersatzlos gelöscht worden. Sie verlangte
   * `salesChannel === 'WEB'`, und seit dem Kahlschlag der Fremdwelten in 0.4.0
   * schreibt niemand mehr WEB — sie war also unerreichbar. Schlimmer: sie
   * schrieb fiskale Zeilen, ohne vorher zu prüfen, ob überhaupt eine
   * Sicherungseinrichtung eingerichtet ist.
   *
   * Der Satz oben behauptete danach, ein Pfad sei fiskal relevant, den es gar
   * nicht mehr gibt. Das ist die Hausklasse „Wächter mit Namensliste wird
   * blind", nur andersherum: ein Eintrag ohne Route wird nie zu einem echten
   * Aufruf, und die grüne Zeile suggeriert eine Abdeckung, die leer ist.
   *
   * ⛔ Diesen Eintrag NICHT wieder aufnehmen, solange es keine Retourenroute
   * gibt. Kommt sie zurück, gehört sie in dieselbe Schleife wie die anderen
   * drei — und zwar erst, nachdem sie durch `istSicherungseinrichtungEingerichtet`
   * geht.
   */
  it('kennt keinen Retourenpfad, denn es gibt keine Retourenroute', () => {
    expect(isGobdRelevantPath('/api/transactions/return')).toBe(false);
  });

  /**
   * ⛔ DIE PFADE, DIE DER KLIENT WIRKLICH BAUT — BEFUND VOM 12.08.2026
   *
   * Hier standen `/api/cash-movements` und `/api/shifts/close`. Beide gibt es
   * nicht; `domains/shifts.ts` baut die Kennung IN DIE MITTE. Der Prüfsatz
   * bestätigte also erfundene Pfade und blieb grün, während die echten durch
   * die Erkennung fielen — die Hausklasse „der Prüfstand macht denselben
   * Fehler".
   *
   * Die Kennungen sind ABGESCHRIEBENE Formen, keine importierten: eine
   * importierte Zeichenkette stimmte immer mit sich selbst überein.
   */
  it('⛔ erkennt die ECHTEN Schicht-Wege mit der Kennung IN DER MITTE', () => {
    for (const p of [
      '/api/shifts/018f2b6c-7e4a-7c3d-9a1b-2c3d4e5f6a7b/cash-movements',
      '/api/shifts/018f2b6c-7e4a-7c3d-9a1b-2c3d4e5f6a7b/close',
    ]) {
      expect(
        isGobdRelevantPath(p),
        `${p} gilt als NICHT fiskalisch — Kassenbuch und Z-Bon bekämen 30 Tage ` +
          'Aufbewahrung statt zehn Jahren (§ 147 AO)',
      ).toBe(true);
    }
  });

  it('die früher gelisteten, aber nie existierenden Pfade bleiben ohne Wirkung', () => {
    // Sie standen bis zum 12.08.2026 in der Liste und trafen nie etwas. Der
    // Satz hält fest, dass ihr Verschwinden nichts kaputt macht.
    for (const p of ['/api/cash-movements', '/api/shifts/close']) {
      expect(isGobdRelevantPath(p)).toBe(false);
    }
  });

  it('does not flag non-fiscal reads/mutations (incl. the un-prefixed legacy paths)', () => {
    for (const p of [
      '/api/products',
      '/api/inventory/adjust',
      '/api/dashboard/summary',
      '/api/transactions/recent',
      // The old un-prefixed forms must NOT match — they were the retention bug.
      '/ankauf',
      '/transactions/finalize',
    ]) {
      expect(isGobdRelevantPath(p)).toBe(false);
    }
  });
});

describe('drainOutbox — replay loop (ADR-0044 §6, action items 4 & 5)', () => {
  it('replays all pending rows in FIFO order on success and marks each succeeded', async () => {
    const pending = [makeRecord('a'), makeRecord('b'), makeRecord('c')];
    const store = createReplayStore(pending);
    const seen: string[] = [];
    const replay = vi.fn(async (r: OutboxRecord) => {
      seen.push(r.idempotencyKey);
      return { ok: true };
    });

    const outcome = await drainOutbox({ store, replay });

    expect(outcome.kind).toBe('drained');
    expect(seen).toEqual(['a', 'b', 'c']);
    expect(store.succeeded).toEqual(['a', 'b', 'c']);
    expect(store.conflicts).toEqual([]);
  });

  it('aborts the run on ApiNetworkError, leaving the row pending (no conflict)', async () => {
    const pending = [makeRecord('a'), makeRecord('b')];
    const store = createReplayStore(pending);
    const replay = vi.fn(async (r: OutboxRecord) => {
      if (r.idempotencyKey === 'b') throw new ApiNetworkError('offline again');
      return { ok: true };
    });

    const outcome = await drainOutbox({ store, replay });

    expect(outcome.kind).toBe('aborted');
    expect(store.succeeded).toEqual(['a']);
    expect(store.conflicts).toEqual([]);
    // 'b' was NOT marked anything — it stays pending for the next online event.
  });

  it('aborts (not halts) on a 5xx — server trouble is transient', async () => {
    const store = createReplayStore([makeRecord('a')]);
    const replay = vi.fn(async () => {
      throw new ApiError({ code: 'INTERNAL_ERROR', message: 'boom', httpStatus: 503 });
    });

    const outcome = await drainOutbox({ store, replay });

    expect(outcome.kind).toBe('aborted');
    expect(store.conflicts).toEqual([]);
  });

  it('aborts (not halts) on an auth gap — no session to replay under', async () => {
    const store = createReplayStore([makeRecord('a')]);
    const replay = vi.fn(async () => {
      throw new ApiError({ code: 'UNAUTHORIZED', message: 'no session', httpStatus: 401 });
    });

    const outcome = await drainOutbox({ store, replay });

    expect(outcome.kind).toBe('aborted');
    expect(store.conflicts).toEqual([]);
    expect(store.succeeded).toEqual([]);
  });

  it('HALTS on a conflict: marks the row conflict, fires onConflict, and stops before later rows', async () => {
    const pending = [makeRecord('a'), makeRecord('bad'), makeRecord('c')];
    const store = createReplayStore(pending);
    const onConflict = vi.fn();
    const seen: string[] = [];
    const replay = vi.fn(async (r: OutboxRecord) => {
      seen.push(r.idempotencyKey);
      if (r.idempotencyKey === 'bad') {
        throw new ApiError({
          code: 'CLOSING_DAY_FINALIZED',
          message: 'Tagesabschluss locked',
          httpStatus: 409,
        });
      }
      return { ok: true };
    });

    const outcome = await drainOutbox({ store, replay, onConflict });

    expect(outcome.kind).toBe('halted');
    if (outcome.kind === 'halted') {
      expect(outcome.record.idempotencyKey).toBe('bad');
      expect(outcome.error).toBeInstanceOf(ApiOutboxConflictError);
      expect(outcome.error.serverCode).toBe('CLOSING_DAY_FINALIZED');
    }
    // 'a' succeeded, 'bad' marked conflict, 'c' never attempted.
    expect(seen).toEqual(['a', 'bad']);
    expect(store.succeeded).toEqual(['a']);
    expect(store.conflicts).toEqual(['bad']);
    expect(onConflict).toHaveBeenCalledTimes(1);
  });

  it('treats a generic 409 CONFLICT (STATE_DIVERGED) as a halt', async () => {
    const store = createReplayStore([makeRecord('x')]);
    const replay = vi.fn(async () => {
      throw new ApiError({ code: 'CONFLICT', message: 'diverged', httpStatus: 409 });
    });

    const outcome = await drainOutbox({ store, replay });

    expect(outcome.kind).toBe('halted');
    expect(store.conflicts).toEqual(['x']);
  });

  it('returns drained with succeeded=0 on an empty queue', async () => {
    const store = createReplayStore([]);
    const replay = vi.fn();
    const outcome = await drainOutbox({ store, replay });
    expect(outcome).toEqual({ kind: 'drained', succeeded: 0 });
    expect(replay).not.toHaveBeenCalled();
  });
});
