/**
 * Reusable column-builder helpers — keep table definitions tight and consistent.
 *
 * Every business table in Warehouse14 carries `id UUID PRIMARY KEY` and a
 * `created_at` + `updated_at` audit pair. These helpers centralize the pattern
 * so a future change (e.g. moving to ULIDs, swapping `now()` for a custom
 * clock fn) is one edit, not 12.
 */

import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Standard primary key column: UUID generated by `gen_random_uuid()`
 * (pgcrypto, enabled in migration 0001).
 *
 * @example
 *   id: primaryKey(),
 */
export const primaryKey = () => uuid('id').primaryKey().default(sql`gen_random_uuid()`);

/**
 * Standard audit timestamps. Apply at the end of every business table.
 *
 * `updated_at` is maintained by the `set_updated_at()` trigger function
 * (migration 0002) — apply the trigger in the table's migration.
 *
 * @example
 *   ...timestamps(),
 */
export const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
