-- ═════════════════════════════════════════════════════════════════════════
-- 0096 — erasure must reach the mail queue, and the queue must know who
--        a letter belongs to.
-- ═════════════════════════════════════════════════════════════════════════
--
-- FOUND 2026-07-22, minutes after the Google Workspace relay was switched on
-- and a two-day backlog of ten letters flushed in one tick. One of those
-- letters belonged to an account that had been erased the night before under
-- Art. 17. It was delivered anyway.
--
-- Two defects, one cause:
--
--   1. `email_outbox` has no customer_id. It never had one, so erasure had
--      no way to find a person's letters even in principle.
--   2. `erase_customer()` therefore did not sweep it. The table holds the
--      recipient address (encrypted) plus the rendered subject and body,
--      which carry the person's name and reservation number in clear text.
--      All of it survived erasure, indefinitely.
--
-- This is the same class of hole as 0094, which found `shoppers` untouched
-- by the same function. Erasure is only as complete as the list of tables
-- somebody remembered to write down.
--
-- Nothing about the legal position changes: fiscal and GoBD records keep
-- their retention under § 147 AO and § 257 HGB via Art. 17(3)(b). A welcome
-- letter is not a fiscal record and enjoys no such protection.
-- ═════════════════════════════════════════════════════════════════════════

-- ── 1. Give the queue a subject ─────────────────────────────────────────
-- Nullable on purpose: a letter may outlive the customer row, and ON DELETE
-- SET NULL keeps a hard customer delete from cascading into the delivery log.
ALTER TABLE email_outbox
  ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES customers(id) ON DELETE SET NULL;

-- The only read pattern is "this person's letters", driven by erasure.
CREATE INDEX IF NOT EXISTS email_outbox_customer_idx
  ON email_outbox (customer_id) WHERE customer_id IS NOT NULL;

-- ── 2. Drop what cannot be attributed ───────────────────────────────────
-- Every row predating this migration has customer_id NULL and no way to
-- recover it: the recipient is encrypted with a non-deterministic scheme and
-- the table carries no blind index to match on. At the time of writing that
-- is exactly ten rows, all SENT, all generated by our own testing on
-- 2026-07-20 and 2026-07-21 — and one of them belongs to the account erased
-- on 2026-07-21. That person's erasure cannot be honoured by lookup, so it
-- is honoured by dropping the whole unattributable set.
--
-- Deleted rather than scrubbed in place, deliberately. recipient_encrypted is
-- bytea NOT NULL and encrypt_pii() is unavailable here — a plain migration has
-- no pii key in its session — so a scrub would have to write a placeholder
-- that is not valid ciphertext, and decrypt_pii() raises "Wrong key or corrupt
-- data" the moment anything reads the column across the whole table. That is a
-- landmine for any later export or admin query, planted to preserve ten rows of
-- test mail that carry no business or fiscal value. The queue is not a fiscal
-- record; § 147 AO does not reach it.
DELETE FROM email_outbox WHERE customer_id IS NULL;

-- ── 3. Teach erasure about the queue ────────────────────────────────────
-- Body below is the live 0095 function verbatim, plus the mail-queue block.
CREATE OR REPLACE FUNCTION public.erase_customer(p_customer_id uuid, p_actor uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$

DECLARE
  v_phone     TEXT;
  v_kyc_keys  TEXT[] := '{}';
  v_r2_keys   TEXT[] := '{}';
BEGIN
  -- The subject must exist.
  PERFORM 1 FROM customers WHERE id = p_customer_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'customer % not found', p_customer_id USING ERRCODE = 'no_data_found';
  END IF;

  -- Resolve the subject phone for the phone-keyed WhatsApp sweeps (best-effort;
  -- NULL if no phone on file → those sweeps are skipped).
  SELECT decrypt_pii(phone_encrypted) INTO v_phone FROM customers WHERE id = p_customer_id;

  -- ── Collect file keys BEFORE scrubbing (caller unlinks post-commit) ──────────
  SELECT COALESCE(array_agg(document_photo_storage_key)
           FILTER (WHERE document_photo_storage_key IS NOT NULL), '{}')
    INTO v_kyc_keys FROM kyc_documents WHERE customer_id = p_customer_id;

  SELECT COALESCE(array_agg(r2_key) FILTER (WHERE r2_key IS NOT NULL), '{}')
    INTO v_r2_keys FROM document_attachments WHERE customer_id = p_customer_id;
  v_r2_keys := v_r2_keys || COALESCE((
    SELECT array_agg(k)
      FROM appraisal_items ai
      JOIN appraisals a ON a.id = ai.appraisal_id
      CROSS JOIN LATERAL unnest(ai.photo_r2_keys) AS k
     WHERE a.customer_id = p_customer_id
  ), '{}');

  -- ── Phase 2 — scrub CHILDREN first (so a failure never leaves the master
  --    flagged-anonymized while children still hold PII) ────────────────────────

  -- appointments: registered + walk-in plaintext contact fields + free-text notes
  UPDATE appointments
     SET contact_name = NULL, contact_phone = NULL, contact_email = NULL,
         customer_notes = NULL, staff_notes = NULL, cancellation_reason = NULL
   WHERE customer_id = p_customer_id;

  -- appointment_notifications: recipient is NOT NULL → sentinel, never NULL
  UPDATE appointment_notifications
     SET recipient = 'REDACTED', external_ref = NULL
   WHERE appointment_id IN (SELECT id FROM appointments WHERE customer_id = p_customer_id);

  -- WhatsApp (phone-keyed). NOT NULL / non-empty / object CHECKs → sentinels.
  IF v_phone IS NOT NULL THEN
    UPDATE whatsapp_inbound_messages
       SET body_encrypted = NULL, processing_error = NULL,
           raw_payload = '{}'::jsonb, from_phone = 'REDACTED'
     WHERE from_phone = v_phone;
    UPDATE whatsapp_outbound_messages
       SET body = '–', body_encrypted = NULL, template_params = NULL,
           to_phone = 'REDACTED',
           provider_error = CASE WHEN status = 'failed' THEN '{}'::jsonb ELSE NULL END
     WHERE to_phone = v_phone;
  END IF;
  UPDATE whatsapp_conversations
     SET customer_id = NULL, anonymized_at = now(),
         customer_phone_e164 = 'erased:' || id
   WHERE customer_id = p_customer_id;

  -- appraisals / appraisal_items
  UPDATE appraisals
     SET notes = NULL,
         rejection_reason = CASE WHEN status = 'REJECTED' THEN 'GELOESCHT' ELSE NULL END
   WHERE customer_id = p_customer_id;
  UPDATE appraisal_items
     SET notes = NULL, description = NULL, photo_r2_keys = '{}'
   WHERE appraisal_id IN (SELECT id FROM appraisals WHERE customer_id = p_customer_id);

  -- products acquired from this customer
  UPDATE products
     SET provenance_notes = NULL, acquired_from_customer_id = NULL
   WHERE acquired_from_customer_id = p_customer_id;

  -- vouchers (keep the row — §3(14) UStG — only the free-text note is PII)
  UPDATE vouchers SET notes = NULL WHERE issued_to_customer_id = p_customer_id;

  -- document_attachments: keep customer_id (link CHECKs) + fiscal category; the
  -- file refs are NOT NULL with length CHECKs → sentinel, never NULL.
  UPDATE document_attachments
     SET r2_key = 'erased', file_name = 'erased', sha256_hex = NULL,
         notes = NULL, archived_at = COALESCE(archived_at, now())
   WHERE customer_id = p_customer_id;

  -- kyc_documents purge — ALL-OR-NOTHING per kyc_documents_purged_consistency;
  -- purged_by_user_id is NOT NULL in the purged branch.
  UPDATE kyc_documents
     SET document_number_encrypted = NULL, document_photo_sha256 = NULL,
         document_photo_storage_key = NULL, document_photo_size_bytes = NULL,
         purged_at = now(), purged_by_user_id = p_actor
   WHERE customer_id = p_customer_id AND purged_at IS NULL;

  -- transactions: keep the fiscal row; NULL only the embedded PII. NEVER NULL
  -- customer_id (the storno-validator trigger matches on it).
  UPDATE transactions
     SET shipping_address_encrypted = NULL, notes_internal = NULL
   WHERE customer_id = p_customer_id;

  -- internal_tasks pointing at the customer (clear the pointer as a PAIR)
  UPDATE internal_tasks
     SET related_entity_table = NULL, related_entity_id = NULL,
         title = 'Gelöscht', description = NULL,
         cancellation_reason = CASE WHEN status = 'CANCELLED'
                                    THEN COALESCE(cancellation_reason, 'gelöscht') ELSE NULL END
   WHERE related_entity_table = 'customers' AND related_entity_id = p_customer_id;

  -- mcp_tool_invocations referencing the subject
  UPDATE mcp_tool_invocations
     SET arguments = '{}'::jsonb, error_message = NULL,
         result = CASE WHEN outcome = 'SUCCESS' THEN '{}'::jsonb ELSE NULL END
   WHERE affected_entity_table IN ('customers', 'shoppers') AND affected_entity_id = p_customer_id;

  -- ── The transactional mail queue ────────────────────────────────────────
  -- ADDED 0096, and it had misfired in production before it was found.
  -- email_outbox stores the recipient address encrypted, and the rendered
  -- subject and body carry the person's name and reservation number in clear
  -- text. Erasure never touched this table, so two things were true at once:
  -- an erased customer's address and name survived here in full, and any
  -- letter still PENDING was delivered to them AFTER they had exercised
  -- Art. 17. The second one actually happened on 2026-07-22, when the Google
  -- relay was switched on and a two-day backlog flushed, including letters
  -- belonging to an account erased the night before.
  --
  -- The table could not even be swept before now: it carried no customer_id.
  -- This migration adds one, which is what makes the block below possible.
  --
  -- PENDING letters are dropped outright — there is no lawful basis for
  -- writing to someone who has asked to be forgotten. SENT and FAILED rows
  -- keep their skeleton so the delivery log stays auditable, with every
  -- personal field overwritten and the link to the person cut.
  DELETE FROM email_outbox
   WHERE customer_id = p_customer_id AND status = 'PENDING';

  UPDATE email_outbox
     SET recipient_encrypted = encrypt_pii('GELOESCHT'),
         subject     = 'Geloescht',
         body_text   = '-',
         body_html   = NULL,
         last_error  = NULL,
         customer_id = NULL
   WHERE customer_id = p_customer_id;

  -- ── Phase 3 — the customers MASTER last, one UPDATE satisfying all CHECKs ─────
  --  • full_name_encrypted is NOT NULL → encrypted tombstone, never NULL.
  --  • trust_level reset to NEW so customers_banned_or_suspicious_has_note holds
  --    once price_expectation_notes is NULLed.
  --  • soft_deleted_at THEN anonymized_at (ordering CHECKs; equal ts satisfies >=).
  --  • customer_number + cumulative_* (trigger-only) are kept untouched.
  -- ── The storefront login row ────────────────────────────────────────────
  -- ADDED 0094. This block did not exist, and its absence was the whole hole:
  -- erasure scrubbed fourteen tables and left `shoppers` untouched, so an
  -- "erased" customer kept their e-mail, phone, shipping address, password
  -- hash and Google subject id in full. The schema had clearly intended
  -- otherwise: shoppers.anonymized_at and the CHECK that pairs it with
  -- soft_deleted_at were already there, waiting for a writer that never came.
  --
  -- email_encrypted and email_blind_index are NOT NULL, so they take a
  -- tombstone rather than NULL. That is safe against the unique index because
  -- shoppers_email_blind_active_uq is PARTIAL (WHERE soft_deleted_at IS NULL),
  -- so every erased row drops out of it.
  --
  -- Both credentials are cleared, which would violate shoppers_has_credential
  -- on its own; is_guest = TRUE satisfies it and is the honest description of
  -- what the row now is. Clearing google_sub also matters on its own: leaving
  -- it would let the same Google account sign back in and land on the erased
  -- record.
  UPDATE shoppers
     SET email_encrypted    = encrypt_pii('GELOESCHT'),
         email_blind_index  = blind_index('geloescht'),
         phone_encrypted    = NULL,
         phone_blind_index  = NULL,
         given_name_encrypted  = NULL,
         family_name_encrypted = NULL,
         picture_url_encrypted = NULL,
         shipping_recipient_name_encrypted = NULL,
         shipping_address_line1_encrypted  = NULL,
         shipping_address_line2_encrypted  = NULL,
         shipping_postal_code_encrypted    = NULL,
         shipping_city_encrypted           = NULL,
         shipping_country                  = NULL,
         billing_recipient_name_encrypted  = NULL,
         billing_address_line1_encrypted   = NULL,
         billing_address_line2_encrypted   = NULL,
         billing_postal_code_encrypted     = NULL,
         billing_city_encrypted            = NULL,
         billing_country                   = NULL,
         password_hash             = NULL,
         google_sub                = NULL,
         email_verification_token  = NULL,
         email_verified_at         = NULL,
         marketing_consent         = FALSE,
         is_guest                  = TRUE,
         last_seen_at              = NULL,
         soft_deleted_at = COALESCE(soft_deleted_at, now()),
         anonymized_at   = now(),
         updated_at      = now()
   WHERE customer_id = p_customer_id;

  -- Any session still open dies with the identity. shopper_sessions has no
  -- revoked_at: that column belongs to the STAFF sessions table (0089), not
  -- this one. A shopper session is a bearer token and nothing else, so the
  -- row is simply deleted, which is stronger than expiring it anyway.
  DELETE FROM shopper_sessions ss
   USING shoppers s
   WHERE s.customer_id = p_customer_id
     AND ss.shopper_id = s.id;

  UPDATE customers
     SET full_name_encrypted   = encrypt_pii('GELOESCHT'),
         date_of_birth_encrypted = NULL, email_encrypted = NULL, phone_encrypted = NULL,
         address_encrypted = NULL, notes_encrypted = NULL,
         email_blind_index = NULL, phone_blind_index = NULL,
         vat_id = NULL, customer_tags = '{}', price_expectation_notes = NULL,
         trust_level = 'NEW',
         soft_deleted_at = COALESCE(soft_deleted_at, now()),
         anonymized_at = now()
   WHERE id = p_customer_id;

  RETURN jsonb_build_object(
    'kyc_storage_keys', to_jsonb(v_kyc_keys),
    'r2_keys',          to_jsonb(v_r2_keys)
  );
END;

$function$;
